name: Ubuntu
on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'main.cpp'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'main.cpp'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        qt_ver: [6.5.0]
        qt_arch: [gcc_64]
        exclude:
          - os: ubuntu-18.04
            qt_ver: 6.2.2
            qt_arch: gcc_64
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
          modules: 'qtmultimedia'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: create build
        run: cmake -B build
      - name: make
        run: cmake --build build
      - uses: actions/upload-artifact@v2
        with:
          name: appcountdown-qml
          path: build/appcountdown-qml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/appcountdown-qml
